TERMUX_PKG_HOMEPAGE=https://www.isc.org/bind/
TERMUX_PKG_DESCRIPTION="DNS tools"
TERMUX_PKG_LICENSE="GPL-3.0"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_SHA256=13697b33e1a43bd4831e57aa685025c6352b8886f9c29cd004a6d4ecd29c5f2c
TERMUX_PKG_VERSION=9.19.5
TERMUX_PKG_REVISION=1
TERMUX_PKG_SRCURL=https://downloads.isc.org/isc/bind9/${TERMUX_PKG_VERSION}/bind-${TERMUX_PKG_VERSION}.tar.xz
TERMUX_PKG_DEPENDS="libcrypt, libuv, openssl, zlib, nghttp2"
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_EXTRA_CONFIGURE_ARGS="
--disable-linux-caps
--disable-static
"
